const enum WS_MESSAGE_TYPE {
  NAVIGATE, 
  OFFER_REROUTE, 
  ACCEPT_REROUTE, 
  UPDATE_NAV_DETAILS, 
  UPDATE_POSITION, 
  UPDATE_INSTRUCTION, 
  CANCEL_NAVIGATION, 
}

export default WS_MESSAGE_TYPE;