const enum WS_MESSAGE_TYPE {
  SEND_NAV_ID, 
  REQUEST_NAVIGATE, 
  SEND_PATH, 
  OFFER_REROUTE, 
  ACCEPT_REROUTE, 
  UPDATE_POSITION, 
  UPDATE_INSTRUCTION, 
  CANCEL_NAVIGATION, 
}

export default WS_MESSAGE_TYPE;