const enum REROUTE_REASON {
  LOCATION_CHANGED = "LOCATION CHANGED", 
  INFRASTRUCTURE_CHANGED = "INFRASTRUCTURE_CHANGED", 
  AMENITIES_CHANGED = "AMENITIES_CHANGED", 
}

export default REROUTE_REASON;